spring:
  config:
    import:
      - classpath:redis.yaml
      - classpath:kafka.yaml
      - classpath:mariadb.yaml
      - classpath:jpa.yaml
      - classpath:docker.yaml
      - classpath:cache.yaml
      - resilience4j.yaml
      - classpath:logging.yaml