# Database
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        default_batch_fetch_size: 30
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate
    open-in-view: false