services:
  redis:
    image: 'redis:latest'
    restart: 'always'
    ports:
      - '6379:6379'
  mariadb:
    image: 'mariadb'
    restart: 'always'
    environment:
      MARIADB_DATABASE: 'circuit'
      MARIADB_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  zookeeper:
    image: 'wurstmeister/zookeeper'
    platform: 'linux/amd64'
    restart: 'always'
    container_name: 'zookeeper'
    ports:
      - "2181:2181"
  kafka:
    image: 'wurstmeister/kafka'
    restart: 'always'
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: 'PLAINTEXT://:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'