spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 601228381168-5kk3sqkepu2vbuumdd2rch68iebriemq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile